version: '3.8'
services:
    php-environment:
        container_name: webapp
        build:
            context: ./project-jenkins
            dockerfile: Dockerfile
        depends_on:
            - db1
        volumes:
            - ./project-jenkins:/var/www/html/
        ports:
            - 8000:80
    db1:
        container_name: db1
        image: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: true  # You can use this line if you want an empty password for root
          MYSQL_DATABASE: hive
        ports:
            - "9906:3306"